//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solutran.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Request", Namespace="http://schemas.datacontract.org/2004/07/Solutran.S3.Service.Models")]
    [System.SerializableAttribute()]
    public partial class Request : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Solutran.ServiceReference1.TransInfo TransInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Solutran.ServiceReference1.TransInfo TransInfo {
            get {
                return this.TransInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.TransInfoField, value) != true)) {
                    this.TransInfoField = value;
                    this.RaisePropertyChanged("TransInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransInfo", Namespace="http://schemas.datacontract.org/2004/07/Solutran.S3.Common.Entities.Messaging")]
    [System.SerializableAttribute()]
    public partial class TransInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string APLVerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Solutran.ServiceReference1.BalanceInfo[] BalanceInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BusDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Solutran.ServiceReference1.CardInfo[] CardInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrCdeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Solutran.ServiceReference1.DiscountInfo[] DiscountInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocalDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Solutran.ServiceReference1.ProductInfo[] ProductInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Solutran.ServiceReference1.RecptInfo[] RecptInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RetaiLocField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string S3CardCtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string S3MerchIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string S3ProdCtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal S3PurAmtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string S3RecMessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string S3TranIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TermIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TermTranIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalTaxAmtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalTranAmtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalTranDiscField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VerTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string APLVer {
            get {
                return this.APLVerField;
            }
            set {
                if ((object.ReferenceEquals(this.APLVerField, value) != true)) {
                    this.APLVerField = value;
                    this.RaisePropertyChanged("APLVer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActionCode {
            get {
                return this.ActionCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionCodeField, value) != true)) {
                    this.ActionCodeField = value;
                    this.RaisePropertyChanged("ActionCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Solutran.ServiceReference1.BalanceInfo[] BalanceInfo {
            get {
                return this.BalanceInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.BalanceInfoField, value) != true)) {
                    this.BalanceInfoField = value;
                    this.RaisePropertyChanged("BalanceInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BusDate {
            get {
                return this.BusDateField;
            }
            set {
                if ((object.ReferenceEquals(this.BusDateField, value) != true)) {
                    this.BusDateField = value;
                    this.RaisePropertyChanged("BusDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Solutran.ServiceReference1.CardInfo[] CardInfo {
            get {
                return this.CardInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.CardInfoField, value) != true)) {
                    this.CardInfoField = value;
                    this.RaisePropertyChanged("CardInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrCde {
            get {
                return this.CurrCdeField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrCdeField, value) != true)) {
                    this.CurrCdeField = value;
                    this.RaisePropertyChanged("CurrCde");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Solutran.ServiceReference1.DiscountInfo[] DiscountInfo {
            get {
                return this.DiscountInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.DiscountInfoField, value) != true)) {
                    this.DiscountInfoField = value;
                    this.RaisePropertyChanged("DiscountInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocalDateTime {
            get {
                return this.LocalDateTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.LocalDateTimeField, value) != true)) {
                    this.LocalDateTimeField = value;
                    this.RaisePropertyChanged("LocalDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessType {
            get {
                return this.MessTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MessTypeField, value) != true)) {
                    this.MessTypeField = value;
                    this.RaisePropertyChanged("MessType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderIDField, value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Solutran.ServiceReference1.ProductInfo[] ProductInfo {
            get {
                return this.ProductInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductInfoField, value) != true)) {
                    this.ProductInfoField = value;
                    this.RaisePropertyChanged("ProductInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Solutran.ServiceReference1.RecptInfo[] RecptInfo {
            get {
                return this.RecptInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.RecptInfoField, value) != true)) {
                    this.RecptInfoField = value;
                    this.RaisePropertyChanged("RecptInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RetaiLoc {
            get {
                return this.RetaiLocField;
            }
            set {
                if ((object.ReferenceEquals(this.RetaiLocField, value) != true)) {
                    this.RetaiLocField = value;
                    this.RaisePropertyChanged("RetaiLoc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string S3CardCt {
            get {
                return this.S3CardCtField;
            }
            set {
                if ((object.ReferenceEquals(this.S3CardCtField, value) != true)) {
                    this.S3CardCtField = value;
                    this.RaisePropertyChanged("S3CardCt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string S3MerchID {
            get {
                return this.S3MerchIDField;
            }
            set {
                if ((object.ReferenceEquals(this.S3MerchIDField, value) != true)) {
                    this.S3MerchIDField = value;
                    this.RaisePropertyChanged("S3MerchID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string S3ProdCt {
            get {
                return this.S3ProdCtField;
            }
            set {
                if ((object.ReferenceEquals(this.S3ProdCtField, value) != true)) {
                    this.S3ProdCtField = value;
                    this.RaisePropertyChanged("S3ProdCt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal S3PurAmt {
            get {
                return this.S3PurAmtField;
            }
            set {
                if ((this.S3PurAmtField.Equals(value) != true)) {
                    this.S3PurAmtField = value;
                    this.RaisePropertyChanged("S3PurAmt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string S3RecMess {
            get {
                return this.S3RecMessField;
            }
            set {
                if ((object.ReferenceEquals(this.S3RecMessField, value) != true)) {
                    this.S3RecMessField = value;
                    this.RaisePropertyChanged("S3RecMess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string S3TranID {
            get {
                return this.S3TranIDField;
            }
            set {
                if ((object.ReferenceEquals(this.S3TranIDField, value) != true)) {
                    this.S3TranIDField = value;
                    this.RaisePropertyChanged("S3TranID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TermID {
            get {
                return this.TermIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TermIDField, value) != true)) {
                    this.TermIDField = value;
                    this.RaisePropertyChanged("TermID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TermTranID {
            get {
                return this.TermTranIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TermTranIDField, value) != true)) {
                    this.TermTranIDField = value;
                    this.RaisePropertyChanged("TermTranID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalTaxAmt {
            get {
                return this.TotalTaxAmtField;
            }
            set {
                if ((this.TotalTaxAmtField.Equals(value) != true)) {
                    this.TotalTaxAmtField = value;
                    this.RaisePropertyChanged("TotalTaxAmt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalTranAmt {
            get {
                return this.TotalTranAmtField;
            }
            set {
                if ((this.TotalTranAmtField.Equals(value) != true)) {
                    this.TotalTranAmtField = value;
                    this.RaisePropertyChanged("TotalTranAmt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalTranDisc {
            get {
                return this.TotalTranDiscField;
            }
            set {
                if ((this.TotalTranDiscField.Equals(value) != true)) {
                    this.TotalTranDiscField = value;
                    this.RaisePropertyChanged("TotalTranDisc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VerType {
            get {
                return this.VerTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.VerTypeField, value) != true)) {
                    this.VerTypeField = value;
                    this.RaisePropertyChanged("VerType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BalanceInfo", Namespace="http://schemas.datacontract.org/2004/07/Solutran.S3.Common.Entities.Messaging")]
    [System.SerializableAttribute()]
    public partial class BalanceInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BalUnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal BalValField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BarCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrdinalNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProgCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PromoCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PromoShortField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BalUnit {
            get {
                return this.BalUnitField;
            }
            set {
                if ((object.ReferenceEquals(this.BalUnitField, value) != true)) {
                    this.BalUnitField = value;
                    this.RaisePropertyChanged("BalUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BalVal {
            get {
                return this.BalValField;
            }
            set {
                if ((this.BalValField.Equals(value) != true)) {
                    this.BalValField = value;
                    this.RaisePropertyChanged("BalVal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BarCode {
            get {
                return this.BarCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BarCodeField, value) != true)) {
                    this.BarCodeField = value;
                    this.RaisePropertyChanged("BarCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrdinalNum {
            get {
                return this.OrdinalNumField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdinalNumField, value) != true)) {
                    this.OrdinalNumField = value;
                    this.RaisePropertyChanged("OrdinalNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProgCode {
            get {
                return this.ProgCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProgCodeField, value) != true)) {
                    this.ProgCodeField = value;
                    this.RaisePropertyChanged("ProgCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PromoCode {
            get {
                return this.PromoCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PromoCodeField, value) != true)) {
                    this.PromoCodeField = value;
                    this.RaisePropertyChanged("PromoCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PromoShort {
            get {
                return this.PromoShortField;
            }
            set {
                if ((object.ReferenceEquals(this.PromoShortField, value) != true)) {
                    this.PromoShortField = value;
                    this.RaisePropertyChanged("PromoShort");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardInfo", Namespace="http://schemas.datacontract.org/2004/07/Solutran.S3.Common.Entities.Messaging")]
    [System.SerializableAttribute()]
    public partial class CardInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BarcodeDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CVVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string POSDataCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BarcodeData {
            get {
                return this.BarcodeDataField;
            }
            set {
                if ((object.ReferenceEquals(this.BarcodeDataField, value) != true)) {
                    this.BarcodeDataField = value;
                    this.RaisePropertyChanged("BarcodeData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CVV {
            get {
                return this.CVVField;
            }
            set {
                if ((object.ReferenceEquals(this.CVVField, value) != true)) {
                    this.CVVField = value;
                    this.RaisePropertyChanged("CVV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string POSDataCode {
            get {
                return this.POSDataCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.POSDataCodeField, value) != true)) {
                    this.POSDataCodeField = value;
                    this.RaisePropertyChanged("POSDataCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DiscountInfo", Namespace="http://schemas.datacontract.org/2004/07/Solutran.S3.Common.Entities.Messaging")]
    [System.SerializableAttribute()]
    public partial class DiscountInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AppDiscAmtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeptNrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiscDescrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiscLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrdinalNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProdCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AppDiscAmt {
            get {
                return this.AppDiscAmtField;
            }
            set {
                if ((this.AppDiscAmtField.Equals(value) != true)) {
                    this.AppDiscAmtField = value;
                    this.RaisePropertyChanged("AppDiscAmt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeptNr {
            get {
                return this.DeptNrField;
            }
            set {
                if ((object.ReferenceEquals(this.DeptNrField, value) != true)) {
                    this.DeptNrField = value;
                    this.RaisePropertyChanged("DeptNr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiscDescr {
            get {
                return this.DiscDescrField;
            }
            set {
                if ((object.ReferenceEquals(this.DiscDescrField, value) != true)) {
                    this.DiscDescrField = value;
                    this.RaisePropertyChanged("DiscDescr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiscLevel {
            get {
                return this.DiscLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.DiscLevelField, value) != true)) {
                    this.DiscLevelField = value;
                    this.RaisePropertyChanged("DiscLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrdinalNum {
            get {
                return this.OrdinalNumField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdinalNumField, value) != true)) {
                    this.OrdinalNumField = value;
                    this.RaisePropertyChanged("OrdinalNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProdCode {
            get {
                return this.ProdCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdCodeField, value) != true)) {
                    this.ProdCodeField = value;
                    this.RaisePropertyChanged("ProdCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductInfo", Namespace="http://schemas.datacontract.org/2004/07/Solutran.S3.Common.Entities.Messaging")]
    [System.SerializableAttribute()]
    public partial class ProductInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal NonS3DiscAmtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrdinalNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProdCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProdLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PurQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PurchAmtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuantityTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TaxAmtField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Depart {
            get {
                return this.DepartField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartField, value) != true)) {
                    this.DepartField = value;
                    this.RaisePropertyChanged("Depart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NonS3DiscAmt {
            get {
                return this.NonS3DiscAmtField;
            }
            set {
                if ((this.NonS3DiscAmtField.Equals(value) != true)) {
                    this.NonS3DiscAmtField = value;
                    this.RaisePropertyChanged("NonS3DiscAmt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrdinalNum {
            get {
                return this.OrdinalNumField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdinalNumField, value) != true)) {
                    this.OrdinalNumField = value;
                    this.RaisePropertyChanged("OrdinalNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProdCode {
            get {
                return this.ProdCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdCodeField, value) != true)) {
                    this.ProdCodeField = value;
                    this.RaisePropertyChanged("ProdCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProdLevel {
            get {
                return this.ProdLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdLevelField, value) != true)) {
                    this.ProdLevelField = value;
                    this.RaisePropertyChanged("ProdLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PurQuantity {
            get {
                return this.PurQuantityField;
            }
            set {
                if ((this.PurQuantityField.Equals(value) != true)) {
                    this.PurQuantityField = value;
                    this.RaisePropertyChanged("PurQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PurchAmt {
            get {
                return this.PurchAmtField;
            }
            set {
                if ((this.PurchAmtField.Equals(value) != true)) {
                    this.PurchAmtField = value;
                    this.RaisePropertyChanged("PurchAmt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuantityType {
            get {
                return this.QuantityTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.QuantityTypeField, value) != true)) {
                    this.QuantityTypeField = value;
                    this.RaisePropertyChanged("QuantityType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TaxAmt {
            get {
                return this.TaxAmtField;
            }
            set {
                if ((this.TaxAmtField.Equals(value) != true)) {
                    this.TaxAmtField = value;
                    this.RaisePropertyChanged("TaxAmt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecptInfo", Namespace="http://schemas.datacontract.org/2004/07/Solutran.S3.Common.Entities.Messaging")]
    [System.SerializableAttribute()]
    public partial class RecptInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessOrdinalNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string S3RecptMessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessOrdinalNum {
            get {
                return this.MessOrdinalNumField;
            }
            set {
                if ((object.ReferenceEquals(this.MessOrdinalNumField, value) != true)) {
                    this.MessOrdinalNumField = value;
                    this.RaisePropertyChanged("MessOrdinalNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string S3RecptMess {
            get {
                return this.S3RecptMessField;
            }
            set {
                if ((object.ReferenceEquals(this.S3RecptMessField, value) != true)) {
                    this.S3RecptMessField = value;
                    this.RaisePropertyChanged("S3RecptMess");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/Solutran.S3.Service.Models")]
    [System.SerializableAttribute()]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Solutran.ServiceReference1.TransInfo TransInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Solutran.ServiceReference1.TransInfo TransInfo {
            get {
                return this.TransInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.TransInfoField, value) != true)) {
                    this.TransInfoField = value;
                    this.RaisePropertyChanged("TransInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JsonFault", Namespace="http://schemas.datacontract.org/2004/07/Solutran.S3.Service.Helpers")]
    [System.SerializableAttribute()]
    public partial class JsonFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Solutran.ServiceReference1.TransInfo1 TransInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Solutran.ServiceReference1.TransInfo1 TransInfo {
            get {
                return this.TransInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.TransInfoField, value) != true)) {
                    this.TransInfoField = value;
                    this.RaisePropertyChanged("TransInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransInfo", Namespace="http://schemas.datacontract.org/2004/07/Solutran.S3.Service.Helpers")]
    [System.SerializableAttribute()]
    public partial class TransInfo1 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActionCode {
            get {
                return this.ActionCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionCodeField, value) != true)) {
                    this.ActionCodeField = value;
                    this.RaisePropertyChanged("ActionCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IS3Auth")]
    public interface IS3Auth {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IS3Auth/Process", ReplyAction="http://tempuri.org/IS3Auth/ProcessResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Solutran.ServiceReference1.JsonFault), Action="Error", Name="JsonFault", Namespace="http://schemas.datacontract.org/2004/07/Solutran.S3.Service.Helpers")]
        Solutran.ServiceReference1.Response Process(Solutran.ServiceReference1.Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IS3Auth/Process", ReplyAction="http://tempuri.org/IS3Auth/ProcessResponse")]
        System.Threading.Tasks.Task<Solutran.ServiceReference1.Response> ProcessAsync(Solutran.ServiceReference1.Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IS3Auth/ErrorForGet", ReplyAction="http://tempuri.org/IS3Auth/ErrorForGetResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Solutran.ServiceReference1.JsonFault), Action="Error", Name="JsonFault", Namespace="http://schemas.datacontract.org/2004/07/Solutran.S3.Service.Helpers")]
        void ErrorForGet();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IS3Auth/ErrorForGet", ReplyAction="http://tempuri.org/IS3Auth/ErrorForGetResponse")]
        System.Threading.Tasks.Task ErrorForGetAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IS3Auth/ErrorForPost", ReplyAction="http://tempuri.org/IS3Auth/ErrorForPostResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Solutran.ServiceReference1.JsonFault), Action="Error", Name="JsonFault", Namespace="http://schemas.datacontract.org/2004/07/Solutran.S3.Service.Helpers")]
        void ErrorForPost();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IS3Auth/ErrorForPost", ReplyAction="http://tempuri.org/IS3Auth/ErrorForPostResponse")]
        System.Threading.Tasks.Task ErrorForPostAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IS3AuthChannel : Solutran.ServiceReference1.IS3Auth, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class S3AuthClient : System.ServiceModel.ClientBase<Solutran.ServiceReference1.IS3Auth>, Solutran.ServiceReference1.IS3Auth {
        
        public S3AuthClient() {
        }
        
        public S3AuthClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public S3AuthClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public S3AuthClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public S3AuthClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Solutran.ServiceReference1.Response Process(Solutran.ServiceReference1.Request request) {
            return base.Channel.Process(request);
        }
        
        public System.Threading.Tasks.Task<Solutran.ServiceReference1.Response> ProcessAsync(Solutran.ServiceReference1.Request request) {
            return base.Channel.ProcessAsync(request);
        }
        
        public void ErrorForGet() {
            base.Channel.ErrorForGet();
        }
        
        public System.Threading.Tasks.Task ErrorForGetAsync() {
            return base.Channel.ErrorForGetAsync();
        }
        
        public void ErrorForPost() {
            base.Channel.ErrorForPost();
        }
        
        public System.Threading.Tasks.Task ErrorForPostAsync() {
            return base.Channel.ErrorForPostAsync();
        }
    }
}
