//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace POS_Core.IVULottoService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TxServerServiceSoapBinding", Namespace="http://txserver.sut.softekpr.com/1")]
    public partial class TxServerService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback requestIVULotoOperationCompleted;
        
        private System.Threading.SendOrPostCallback requestTxInfoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TxServerService() {
            this.Url = global::POS_Core.Properties.Settings.Default.PrimePOS_Core_IVULottoService_TxServerService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event requestIVULotoCompletedEventHandler requestIVULotoCompleted;
        
        /// <remarks/>
        public event requestTxInfoCompletedEventHandler requestTxInfoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://txserver.sut.softekpr.com/1", ResponseNamespace="http://txserver.sut.softekpr.com/1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IVULoto", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ivuLotoData requestIVULoto([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] transaction transaction) {
            object[] results = this.Invoke("requestIVULoto", new object[] {
                        transaction});
            return ((ivuLotoData)(results[0]));
        }
        
        /// <remarks/>
        public void requestIVULotoAsync(transaction transaction) {
            this.requestIVULotoAsync(transaction, null);
        }
        
        /// <remarks/>
        public void requestIVULotoAsync(transaction transaction, object userState) {
            if ((this.requestIVULotoOperationCompleted == null)) {
                this.requestIVULotoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrequestIVULotoOperationCompleted);
            }
            this.InvokeAsync("requestIVULoto", new object[] {
                        transaction}, this.requestIVULotoOperationCompleted, userState);
        }
        
        private void OnrequestIVULotoOperationCompleted(object arg) {
            if ((this.requestIVULotoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.requestIVULotoCompleted(this, new requestIVULotoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://txserver.sut.softekpr.com/1", ResponseNamespace="http://txserver.sut.softekpr.com/1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public txInfoResponse requestTxInfo([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] txInfoRequest arg0) {
            object[] results = this.Invoke("requestTxInfo", new object[] {
                        arg0});
            return ((txInfoResponse)(results[0]));
        }
        
        /// <remarks/>
        public void requestTxInfoAsync(txInfoRequest arg0) {
            this.requestTxInfoAsync(arg0, null);
        }
        
        /// <remarks/>
        public void requestTxInfoAsync(txInfoRequest arg0, object userState) {
            if ((this.requestTxInfoOperationCompleted == null)) {
                this.requestTxInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrequestTxInfoOperationCompleted);
            }
            this.InvokeAsync("requestTxInfo", new object[] {
                        arg0}, this.requestTxInfoOperationCompleted, userState);
        }
        
        private void OnrequestTxInfoOperationCompleted(object arg) {
            if ((this.requestTxInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.requestTxInfoCompleted(this, new requestTxInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://txserver.sut.softekpr.com/1")]
    public partial class transaction {
        
        private string merchantIdField;
        
        private decimal municipalTaxField;
        
        private bool municipalTaxFieldSpecified;
        
        private decimal stateTaxField;
        
        private bool stateTaxFieldSpecified;
        
        private decimal subTotalField;
        
        private bool subTotalFieldSpecified;
        
        private tenderType tenderTypeField;
        
        private bool tenderTypeFieldSpecified;
        
        private string terminalIdField;
        
        private string terminalPasswordField;
        
        private decimal totalField;
        
        private bool totalFieldSpecified;
        
        private System.DateTime txDateField;
        
        private bool txDateFieldSpecified;
        
        private txType txTypeField;
        
        private bool txTypeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string merchantId {
            get {
                return this.merchantIdField;
            }
            set {
                this.merchantIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal municipalTax {
            get {
                return this.municipalTaxField;
            }
            set {
                this.municipalTaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool municipalTaxSpecified {
            get {
                return this.municipalTaxFieldSpecified;
            }
            set {
                this.municipalTaxFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal stateTax {
            get {
                return this.stateTaxField;
            }
            set {
                this.stateTaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stateTaxSpecified {
            get {
                return this.stateTaxFieldSpecified;
            }
            set {
                this.stateTaxFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal subTotal {
            get {
                return this.subTotalField;
            }
            set {
                this.subTotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool subTotalSpecified {
            get {
                return this.subTotalFieldSpecified;
            }
            set {
                this.subTotalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tenderType tenderType {
            get {
                return this.tenderTypeField;
            }
            set {
                this.tenderTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tenderTypeSpecified {
            get {
                return this.tenderTypeFieldSpecified;
            }
            set {
                this.tenderTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string terminalId {
            get {
                return this.terminalIdField;
            }
            set {
                this.terminalIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string terminalPassword {
            get {
                return this.terminalPasswordField;
            }
            set {
                this.terminalPasswordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalSpecified {
            get {
                return this.totalFieldSpecified;
            }
            set {
                this.totalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime txDate {
            get {
                return this.txDateField;
            }
            set {
                this.txDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool txDateSpecified {
            get {
                return this.txDateFieldSpecified;
            }
            set {
                this.txDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public txType txType {
            get {
                return this.txTypeField;
            }
            set {
                this.txTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool txTypeSpecified {
            get {
                return this.txTypeFieldSpecified;
            }
            set {
                this.txTypeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://txserver.sut.softekpr.com/1")]
    public enum tenderType {
        
        /// <remarks/>
        CASH,
        
        /// <remarks/>
        CREDIT,
        
        /// <remarks/>
        DEBIT,
        
        /// <remarks/>
        EBT,
        
        /// <remarks/>
        ATH,
        
        /// <remarks/>
        UNSPECIFIED_CARD,
        
        /// <remarks/>
        UNKNOWN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://txserver.sut.softekpr.com/1")]
    public enum txType {
        
        /// <remarks/>
        SALE,
        
        /// <remarks/>
        REFUND,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://txserver.sut.softekpr.com/1")]
    public partial class txInfo {
        
        private string controlNumberField;
        
        private System.DateTime drawDateField;
        
        private bool drawDateFieldSpecified;
        
        private string drawNumberField;
        
        private string ivuLottoNumberField;
        
        private decimal municipalTaxField;
        
        private bool municipalTaxFieldSpecified;
        
        private decimal stateTaxField;
        
        private bool stateTaxFieldSpecified;
        
        private decimal subTotalField;
        
        private bool subTotalFieldSpecified;
        
        private tenderType tenderTypeField;
        
        private bool tenderTypeFieldSpecified;
        
        private decimal totalField;
        
        private bool totalFieldSpecified;
        
        private System.DateTime transactionDateField;
        
        private bool transactionDateFieldSpecified;
        
        private txType transactionTypeField;
        
        private bool transactionTypeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string controlNumber {
            get {
                return this.controlNumberField;
            }
            set {
                this.controlNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime drawDate {
            get {
                return this.drawDateField;
            }
            set {
                this.drawDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool drawDateSpecified {
            get {
                return this.drawDateFieldSpecified;
            }
            set {
                this.drawDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string drawNumber {
            get {
                return this.drawNumberField;
            }
            set {
                this.drawNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ivuLottoNumber {
            get {
                return this.ivuLottoNumberField;
            }
            set {
                this.ivuLottoNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal municipalTax {
            get {
                return this.municipalTaxField;
            }
            set {
                this.municipalTaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool municipalTaxSpecified {
            get {
                return this.municipalTaxFieldSpecified;
            }
            set {
                this.municipalTaxFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal stateTax {
            get {
                return this.stateTaxField;
            }
            set {
                this.stateTaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stateTaxSpecified {
            get {
                return this.stateTaxFieldSpecified;
            }
            set {
                this.stateTaxFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal subTotal {
            get {
                return this.subTotalField;
            }
            set {
                this.subTotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool subTotalSpecified {
            get {
                return this.subTotalFieldSpecified;
            }
            set {
                this.subTotalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tenderType tenderType {
            get {
                return this.tenderTypeField;
            }
            set {
                this.tenderTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tenderTypeSpecified {
            get {
                return this.tenderTypeFieldSpecified;
            }
            set {
                this.tenderTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalSpecified {
            get {
                return this.totalFieldSpecified;
            }
            set {
                this.totalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime transactionDate {
            get {
                return this.transactionDateField;
            }
            set {
                this.transactionDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transactionDateSpecified {
            get {
                return this.transactionDateFieldSpecified;
            }
            set {
                this.transactionDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public txType transactionType {
            get {
                return this.transactionTypeField;
            }
            set {
                this.transactionTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transactionTypeSpecified {
            get {
                return this.transactionTypeFieldSpecified;
            }
            set {
                this.transactionTypeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://txserver.sut.softekpr.com/1")]
    public partial class txInfoResponse {
        
        private string errorDetailField;
        
        private int txCountField;
        
        private txInfo[] transactionsField;
        
        private txInfoResponseStatus statusField;
        
        private bool statusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string errorDetail {
            get {
                return this.errorDetailField;
            }
            set {
                this.errorDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int txCount {
            get {
                return this.txCountField;
            }
            set {
                this.txCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("transactions", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public txInfo[] transactions {
            get {
                return this.transactionsField;
            }
            set {
                this.transactionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public txInfoResponseStatus status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://txserver.sut.softekpr.com/1")]
    public enum txInfoResponseStatus {
        
        /// <remarks/>
        SUCCESS,
        
        /// <remarks/>
        AUTHENTICATION_FAILED,
        
        /// <remarks/>
        MISSING_PARAMETERS,
        
        /// <remarks/>
        INVALID_PARAMETERS,
        
        /// <remarks/>
        SERVER_ERROR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://txserver.sut.softekpr.com/1")]
    public partial class txInfoRequest {
        
        private System.DateTime endDateField;
        
        private bool endDateFieldSpecified;
        
        private string merchantIdField;
        
        private System.DateTime startDateField;
        
        private bool startDateFieldSpecified;
        
        private string terminalIdField;
        
        private string terminalPasswordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime endDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool endDateSpecified {
            get {
                return this.endDateFieldSpecified;
            }
            set {
                this.endDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string merchantId {
            get {
                return this.merchantIdField;
            }
            set {
                this.merchantIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime startDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startDateSpecified {
            get {
                return this.startDateFieldSpecified;
            }
            set {
                this.startDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string terminalId {
            get {
                return this.terminalIdField;
            }
            set {
                this.terminalIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string terminalPassword {
            get {
                return this.terminalPasswordField;
            }
            set {
                this.terminalPasswordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://txserver.sut.softekpr.com/1")]
    public partial class ivuLotoData {
        
        private string ivuLotoField;
        
        private string controlNumberField;
        
        private string drawNumberField;
        
        private System.DateTime drawDateField;
        
        private bool drawDateFieldSpecified;
        
        private txPosResponseStatus statusField;
        
        private bool statusFieldSpecified;
        
        private string errorDetailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ivuLoto {
            get {
                return this.ivuLotoField;
            }
            set {
                this.ivuLotoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string controlNumber {
            get {
                return this.controlNumberField;
            }
            set {
                this.controlNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string drawNumber {
            get {
                return this.drawNumberField;
            }
            set {
                this.drawNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime drawDate {
            get {
                return this.drawDateField;
            }
            set {
                this.drawDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool drawDateSpecified {
            get {
                return this.drawDateFieldSpecified;
            }
            set {
                this.drawDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public txPosResponseStatus status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string errorDetail {
            get {
                return this.errorDetailField;
            }
            set {
                this.errorDetailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://txserver.sut.softekpr.com/1")]
    public enum txPosResponseStatus {
        
        /// <remarks/>
        SUCCESS,
        
        /// <remarks/>
        AUTHENTICATION_FAILED,
        
        /// <remarks/>
        MISSING_PARAMETERS,
        
        /// <remarks/>
        INVALID_PARAMETERS,
        
        /// <remarks/>
        SERVER_ERROR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void requestIVULotoCompletedEventHandler(object sender, requestIVULotoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class requestIVULotoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal requestIVULotoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ivuLotoData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ivuLotoData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void requestTxInfoCompletedEventHandler(object sender, requestTxInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class requestTxInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal requestTxInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public txInfoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((txInfoResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591