# .github/workflows/check-build-only.yml

name: .NET Build Check

on:
  push:
    branches: [ "main" ] # Adjust branches as needed
  pull_request:
    branches: [ "*" ]

jobs:
  build-check:
    name: Build Only
    runs-on: windows-latest # Use 'windows-latest' as your project is on Windows

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        # IMPORTANT: Set this to the exact .NET SDK version your project targets.
        # Example: '6.0.x', '7.0.x', '8.0.x', or 'latest'
        dotnet-version: '8.x' # <--- CHANGE THIS TO YOUR PROJECT'S ACTUAL .NET VERSION

    - name: Display .NET SDK info (for debugging)
      run: |
        echo "Listing .NET SDKs..."
        dotnet --list-sdks
        echo "Displaying .NET environment info..."
        dotnet --info

    - name: Restore .NET dependencies
      # Your solution file path: src/PrimePOS/PrimePOS.sln
      run: dotnet restore src/PrimePOS/PrimePOS.sln

    - name: Build .NET solution
      # Your solution file path: src/PrimePOS/PrimePOS.sln
      # Using /v:d for detailed output in case of errors
      run: dotnet build src/PrimePOS/PrimePOS.sln --configuration Debug --no-restore /v:d

    # No CodeQL, no tests, no reports for this basic check
