# .github/workflows/your-workflow-name.yml

name: .NET Build, Test and Report

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  codeql-analysis:
    name: CodeQL Analysis
    runs-on: windows-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        # IMPORTANT: Ensure this matches your project's target .NET version
        dotnet-version: '8.x' # <--- MAKE SURE THIS IS CORRECT (e.g., '6.0.x', '7.0.x', '8.0.x')

    - name: Display .NET SDK info
      run: |
        echo "Listing .NET SDKs..."
        dotnet --list-sdks
        echo "Displaying .NET environment info..."
        dotnet --info

    - name: Restore .NET dependencies
      # Path to your solution file (src/PrimePOS/PrimePOS.sln) is correct here
      run: dotnet restore src/PrimePOS/PrimePOS.sln

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: csharp

    - name: Build .NET solution
      # Path to your solution file (src/PrimePOS/PrimePOS.sln) is correct here
      run: dotnet build src/PrimePOS/PrimePOS.sln --configuration Debug --no-restore /v:d

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
