name: .NET Build and CodeQL Analysis

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  test-execution:
    name: Execute Tests
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet packages
      run: nuget restore ./src/PrimePOS/PrimePOS.sln

    - name: Build solution
      run: msbuild ./src/PrimePOS/PrimePOS.sln /p:Configuration=Release

    - name: Install VSTest Console
      uses: darenm/Setup-VSTest@v1

    - name: Execute xUnit Tests
      run: |
        $testDll = Get-ChildItem -Recurse -Filter "PrimePOSTestCases.dll" | Select-Object -First 1
        $resultsDir = "TestResults"
        mkdir $resultsDir

        vstest.console.exe "$($testDll.FullName)" /Logger:trx /ResultsDirectory:$resultsDir

    - name: Convert TRX to CSV
      run: |
        $trxFile = Get-ChildItem -Path "TestResults" -Filter *.trx | Select-Object -First 1
        $xml = [xml](Get-Content $trxFile.FullName)
        $testResults = $xml.TestRun.Results.UnitTestResult

        $output = foreach ($test in $testResults) {
            [PSCustomObject]@{
                TestName = $test.testName
                Outcome  = $test.outcome
                Duration = $test.duration
            }
        }

        $output | Export-Csv -Path "TestResults\TestResults.csv" -NoTypeInformation

    - name: Upload TRX Results
      uses: actions/upload-artifact@v4
      with:
        name: TestResults_TRX
        path: TestResults/*.trx

    - name: Upload CSV Results
      uses: actions/upload-artifact@v4
      with:
        name: TestResults_CSV
        path: TestResults/TestResults.csv
