name: .NET Build Checking

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build-check:
    name: Verify .NET Build
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet packages
      run: nuget restore ./src/PrimePOS/PrimePOS.sln

    - name: Build code
      run: msbuild ./src/PrimePOS/PrimePOS.sln /p:Configuration=Release
